const controller = require('../controller/controller')
const {Router} = require('express')

const router = Router()
router.get('/login', controller.get_login)
router.post('/login', controller.post_login)
router.get('/signup', controller.get_signup)
router.post('/signup', controller.post_signup)
router.get('/clothes', controller.get_clothes)
router.get('/toys', controller.get_toys)
router.get('/shoes', controller.get_shoes)
router.get('/item-:id', controller.get_oneItem)
router.post('/item-:id', controller.post_oneItem)
router.post('/', controller.post_home)
router.post('/toys', controller.post_toys)
router.post('/clothes', controller.post_clothes)
router.post('/shoes', controller.post_shoes)
router.get('/listcard', controller.get_listcard)
router.get('/clothes-girls', controller.get_clothes_girls)
router.get('/clothes-boys', controller.get_clothes_boys)
router.get('/clothes-pajamas', controller.get_clothes_pajamas)
router.get('/clothes-outing', controller.get_clothes_outing)
router.get('/shoes-boys', controller.get_shoes_boys)
router.get('/shoes-girls', controller.get_shoes_girls)
router.post('/clothes-girls', controller.post_clothes_girls)
router.post('/clothes-boys', controller.post_clothes_boys)
router.post('/clothes-pajamas', controller.post_clothes_pajamas)
router.post('/clothes-outing', controller.post_clothes_outing)
router.post('/shoes-boys', controller.post_shoes_boys)
router.post('/shoes-girls', controller.post_shoes_girls)

router.delete('/listcard', controller.remove_item)
router.get('/logout', controller.get_logout)

module.exports = router